server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mango?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: aA111111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.huawei.l00379880.admin.model
  configuration:
    map-underscore-to-camel-case: true